mkdir -p Rep_plots/Pho_Interact/BGO/10cm  Rep_plots/Pho_Interact/BGO/5cm  Rep_plots/Pho_Interact/BGO/2.5cm  Rep_plots/Pho_Interact/PbWO4/10cm  Rep_plots/Pho_Interact/PbWO4/5cm  Rep_plots/Pho_Interact/PbWO4/2.5cm  Rep_plots/Pho_Interact/GAGG/10cm  Rep_plots/Pho_Interact/GAGG/5cm  Rep_plots/Pho_Interact/GAGG/2.5cm  Rep_plots/Pho_Interact/GAGG/1cm  Rep_plots/Pho_Interact/LaBr3/10cm  Rep_plots/Pho_Interact/LaBr3/5cm  Rep_plots/Pho_Interact/LaBr3/2.5cm  Rep_plots/Pho_Interact/LaBr3/1cm Rep_plots/Pho_Interact/LYSO/10cm  Rep_plots/Pho_Interact/LYSO/5cm  Rep_plots/Pho_Interact/LYSO/2.5cm

mkdir -p Rep_plots/Scintillation/Opt_Pho_Ana/BGO/10cm  Rep_plots/Scintillation/Opt_Pho_Ana/BGO/5cm  Rep_plots/Scintillation/Opt_Pho_Ana/BGO/2.5cm  Rep_plots/Scintillation/Opt_Pho_Ana/PbWO4/10cm  Rep_plots/Scintillation/Opt_Pho_Ana/PbWO4/5cm  Rep_plots/Scintillation/Opt_Pho_Ana/PbWO4/2.5cm  Rep_plots/Scintillation/Opt_Pho_Ana/GAGG/10cm  Rep_plots/Scintillation/Opt_Pho_Ana/GAGG/5cm  Rep_plots/Scintillation/Opt_Pho_Ana/GAGG/2.5cm  Rep_plots/Scintillation/Opt_Pho_Ana/GAGG/1cm  Rep_plots/Scintillation/Opt_Pho_Ana/LaBr3/10cm  Rep_plots/Scintillation/Opt_Pho_Ana/LaBr3/5cm  Rep_plots/Scintillation/Opt_Pho_Ana/LaBr3/2.5cm  Rep_plots/Scintillation/Opt_Pho_Ana/LaBr3/1cm Rep_plots/Scintillation/Opt_Pho_Ana/LYSO/10cm  Rep_plots/Scintillation/Opt_Pho_Ana/LYSO/5cm  Rep_plots/Scintillation/Opt_Pho_Ana/LYSO/2.5cm

mkdir -p Rep_plots/Scintillation/Fits/ItrFit/BGO/10cm  Rep_plots/Scintillation/Fits/ItrFit/BGO/5cm  Rep_plots/Scintillation/Fits/ItrFit/BGO/2.5cm  Rep_plots/Scintillation/Fits/ItrFit/PbWO4/10cm  Rep_plots/Scintillation/Fits/ItrFit/PbWO4/5cm  Rep_plots/Scintillation/Fits/ItrFit/PbWO4/2.5cm  Rep_plots/Scintillation/Fits/ItrFit/GAGG/10cm  Rep_plots/Scintillation/Fits/ItrFit/GAGG/5cm  Rep_plots/Scintillation/Fits/ItrFit/GAGG/2.5cm  Rep_plots/Scintillation/Fits/ItrFit/GAGG/1cm  Rep_plots/Scintillation/Fits/ItrFit/LaBr3/10cm  Rep_plots/Scintillation/Fits/ItrFit/LaBr3/5cm  Rep_plots/Scintillation/Fits/ItrFit/LaBr3/2.5cm  Rep_plots/Scintillation/Fits/ItrFit/LaBr3/1cm Rep_plots/Scintillation/Fits/ItrFit/LYSO/10cm  Rep_plots/Scintillation/Fits/ItrFit/LYSO/5cm  Rep_plots/Scintillation/Fits/ItrFit/LYSO/2.5cm

mkdir -p Rep_plots/Scintillation/Fits/Resol_Resp/BGO/10cm  Rep_plots/Scintillation/Fits/Resol_Resp/BGO/5cm  Rep_plots/Scintillation/Fits/Resol_Resp/BGO/2.5cm Rep_plots/Scintillation/Fits/Resol_Resp/PbWO4/10cm  Rep_plots/Scintillation/Fits/Resol_Resp/PbWO4/5cm  Rep_plots/Scintillation/Fits/Resol_Resp/PbWO4/2.5cm  Rep_plots/Scintillation/Fits/Resol_Resp/GAGG/10cm  Rep_plots/Scintillation/Fits/Resol_Resp/GAGG/5cm  Rep_plots/Scintillation/Fits/Resol_Resp/GAGG/2.5cm  Rep_plots/Scintillation/Fits/Resol_Resp/GAGG/1cm  Rep_plots/Scintillation/Fits/Resol_Resp/LaBr3/10cm  Rep_plots/Scintillation/Fits/Resol_Resp/LaBr3/5cm  Rep_plots/Scintillation/Fits/Resol_Resp/LaBr3/2.5cm  Rep_plots/Scintillation/Fits/Resol_Resp/LaBr3/1cm Rep_plots/Scintillation/Fits/Resol_Resp/LYSO/10cm  Rep_plots/Scintillation/Fits/Resol_Resp/LYSO/5cm  Rep_plots/Scintillation/Fits/Resol_Resp/LYSO/2.5cm

mkdir -p Rep_plots/Scintillation/Fits/txtFiles
